apiVersion: v1
kind: Service
metadata:
  name: micro-network
  namespace: default
  labels:
    name: micro-network
    micro: service
spec:
  type: NodePort
  ports:
  - port: 8085
    protocol: UDP
    name: network
    nodePort: 30038
  - port: 8080
    protocol: TCP
    name: service
    nodePort: 30080
  selector:
    name: micro-network
    micro: service
