name: Push cells

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Build cells
      run: cd service/runtime/cells; bash build.sh